name: CMake on a single platform
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-release:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y ninja-build doctest-dev gcc-13 g++-13

    - name: Configure compiler
      run: sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

    - name: Configure CMake
      run: cmake -DCMAKE_BUILD_TYPE=Release -DDO_COMPILE_TESTS=ON -GNinja -B ${{github.workspace}}/cmake-build-release

    - name: Build
      run: cmake --build ${{github.workspace}}/cmake-build-release

    - name: Run tests
      run: ${{github.workspace}}/cmake-build-release/test/test-runner
